export const ADD_USER_VISIT_COUNT = 'ModuleUserInfo/ADD_VISIT_COUNT'
export const GET_USER_VISIT_TOTAL = 'MODuleUserInfo/GET_VISIT_TOTAL'
export const SET_USER_OPENID = 'MODuleUserInfo/SET_OPENID'
export const GET_ALL_VISIT_TOTAL = 'Global/GET_ALL_VISIT_TOTAL'
export const SET_USER_INFO = 'MODuleUserInfo/SET_USER_INFO'
export const SET_CAR_INFO = 'MODuleUserInfo/SET_CAR_INFO'

export const WXSDK_GET_CONFIG = 'WXSDK/GET_CONFIG'
export const WXSDK_GET_LOCALTION = 'WXSDK/GET_LOCATION'

export const WO_UPDATE_CLIENT_WASHORDER = "WASHORDER/UPDATE_CLIENT_WASHORDER"
export const WO_PAY_WASHORDER_FROM_WALLET = "WASHORDER/PAY_WASHORDER_FROM_WALLET"
export const WO_GET_WASH_ORDER_FROM_WELCOME = "WASHORDER/GET_WASH_ORDER_FROM_WELCOME"

export const USR_UPDATE_CLIENT_CARLIST = "USERINFO/UPDATE_CLIENT_CARLIST"
export const USR_SET_ADD_NEWCAR = "USERINFO/ADD_NEWCAR"

export const SET_WASHORDER_MSG = "ORDERLIST/WASHORDER_MSG"

export const USR_GETUSERWALLETLOGS = "ORDERLIST/GETUSERWALLETLOGS"
